# Generated by Django 2.2.19 on 2022-01-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220113_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slugurl',
            new_name='slug',
        ),
    ]
