# Generated by Django 2.2.9 on 2022-02-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст поста', verbose_name='Текст поста')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата публикации комментария формируется автоматически', verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='Автор комментария поста записывается автоматически', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комметария')),
                ('post', models.ForeignKey(help_text='Пост к которому оставлен комметарийзаписывается автоматически', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Пост к которому оставлен комметарий')),
            ],
        ),
    ]
